//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KuRsAvAAAAA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч товары.
    /// </summary>
    // *** Start programmer edit section *** (ТЧТовары CustomAttributes)

    // *** End programmer edit section *** (ТЧТовары CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч товары")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧТоварыE", new string[] {
            "ТоварыСпр as \'Товары\'",
            "ТоварыСпр.Наим as \'Товар\'",
            "ТоварыСпр.Цена as \'Цена\'",
            "Количество as \'Количество\'"})]
    public class ТЧТовары : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.KuRsAvAAAAA.ТоварыСпр fТоварыСпр;
        
        private IIS.KuRsAvAAAAA.Чек fЧек;
        
        // *** Start programmer edit section *** (ТЧТовары CustomMembers)

        // *** End programmer edit section *** (ТЧТовары CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТовары.Количество CustomAttributes)

        // *** End programmer edit section *** (ТЧТовары.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТовары.Количество Get start)

                // *** End programmer edit section *** (ТЧТовары.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТЧТовары.Количество Get end)

                // *** End programmer edit section *** (ТЧТовары.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТовары.Количество Set start)

                // *** End programmer edit section *** (ТЧТовары.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТЧТовары.Количество Set end)

                // *** End programmer edit section *** (ТЧТовары.Количество Set end)
            }
        }
        
        /// <summary>
        /// Т ч товары.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТовары.ТоварыСпр CustomAttributes)

        // *** End programmer edit section *** (ТЧТовары.ТоварыСпр CustomAttributes)
        [PropertyStorage(new string[] {
                "ТоварыСпр"})]
        [NotNull()]
        public virtual IIS.KuRsAvAAAAA.ТоварыСпр ТоварыСпр
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТовары.ТоварыСпр Get start)

                // *** End programmer edit section *** (ТЧТовары.ТоварыСпр Get start)
                IIS.KuRsAvAAAAA.ТоварыСпр result = this.fТоварыСпр;
                // *** Start programmer edit section *** (ТЧТовары.ТоварыСпр Get end)

                // *** End programmer edit section *** (ТЧТовары.ТоварыСпр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТовары.ТоварыСпр Set start)

                // *** End programmer edit section *** (ТЧТовары.ТоварыСпр Set start)
                this.fТоварыСпр = value;
                // *** Start programmer edit section *** (ТЧТовары.ТоварыСпр Set end)

                // *** End programmer edit section *** (ТЧТовары.ТоварыСпр Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.KuRsAvAAAAA.Чек.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТовары.Чек CustomAttributes)

        // *** End programmer edit section *** (ТЧТовары.Чек CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Чек"})]
        public virtual IIS.KuRsAvAAAAA.Чек Чек
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТовары.Чек Get start)

                // *** End programmer edit section *** (ТЧТовары.Чек Get start)
                IIS.KuRsAvAAAAA.Чек result = this.fЧек;
                // *** Start programmer edit section *** (ТЧТовары.Чек Get end)

                // *** End programmer edit section *** (ТЧТовары.Чек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТовары.Чек Set start)

                // *** End programmer edit section *** (ТЧТовары.Чек Set start)
                this.fЧек = value;
                // *** Start programmer edit section *** (ТЧТовары.Чек Set end)

                // *** End programmer edit section *** (ТЧТовары.Чек Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧТоварыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧТоварыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧТоварыE", typeof(IIS.KuRsAvAAAAA.ТЧТовары));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧТовары.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧТовары CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧТовары CustomAttributes)
    public class DetailArrayOfТЧТовары : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.KuRsAvAAAAA.DetailArrayOfТЧТовары members)

        // *** End programmer edit section *** (IIS.KuRsAvAAAAA.DetailArrayOfТЧТовары members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧТовары by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧТовары.
        /// </summary>
        public DetailArrayOfТЧТовары(IIS.KuRsAvAAAAA.Чек fЧек) : 
                base(typeof(ТЧТовары), ((ICSSoft.STORMNET.DataObject)(fЧек)))
        {
        }
        
        public IIS.KuRsAvAAAAA.ТЧТовары this[int index]
        {
            get
            {
                return ((IIS.KuRsAvAAAAA.ТЧТовары)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.KuRsAvAAAAA.ТЧТовары dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
